version: '2'
volumes:
  bundle:
  node_modules:
  db-data:
    external: false
services:
  app:
    build: ./todos-app
    container_name: app_ror
    volumes:
      - .:/todos-app
    env_file:
      - .env
    platform: linux/amd64
    ports:
      - 3001:3001
  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - 80:80
    depends_on:
      - app
